### ISSUE TITLE
CONTRIB: Setup AllContributors

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#233]
## Plan
- [x] AllContrib: setup + CoreTeam (#363)
- [x] AllContrib: Contributors + extra (#366)
- [x] AllMembers: setup + CoreTeam (#349)
## Tasks

- [x] .all-contributors
   - [x] Setup bot
   - [x] Add CoreTeam
   - [x] Add ex CoreTeam
   - [x] Add Contributors
      - [x] From feedback round
      - [x] From pull-requests
      - [x] From active reviewers
   - [x] Add scripts
   - Upd CONTRIBUTING by additional step
   - [x] Setup config
   - [x] Actualize contributions per contributors
   - [ ] #367

### Reference

- https://allcontributors.org/
- https://github.com/effector/effector/blob/master/.all-contributorsrc

**Comment by azinit** [comment]
About contributors
https://github.com/codesandbox/codesandbox-client/blob/f89852e88e8048074ca4bf83f133b686206fedcb/CONTRIBUTING.md#add-yourself-as-a-contributor

**Comment by azinit** [comment]
![image](https://user-images.githubusercontent.com/42924400/142161096-325c6630-30c8-4ea5-99e4-c2ca72329c2a.png)

**Comment by azinit** [comment]
![image](https://user-images.githubusercontent.com/42924400/142251129-2d7792e5-1d65-4ec7-9f67-8b16d1c7f889.png)

**Comment by azinit** [comment]
![image](https://user-images.githubusercontent.com/42924400/142354888-d083f14b-54e7-4fe3-9081-572f4b26218c.png)
