### ISSUE TITLE
DISCOVERY: Restructure doc (basely)

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#294]
> @azinit: **Decompose if needed!**

## Description

- [x] `S1` Research and impl draft solution
- [x] `S1` Decompose task
- [x] `S2` Get feedback about draft
- [x] `S2` Get feedback about popular pages from metrics
- [x] `S2` Iterate by tasks:
   - [x] #332
   - [x] #320
   - [x] #321
   - [x] #322
   - [x] #323
   - [x] #324
   - [x] #334
- [x] Additional tasks:
   - [x] #446
   - [ ] #447

<details>
<summary>Steps</summary>

- Swap specific articles
- Merge/Split specific articles
- Update redirects
- Update reference links (Index-page, instead of concrete pages)
   - Remove old cross-linking to sections
- Update both locales (ru, en)
- (Basely) Refine intro
   -  NavPointers (title, emojii, links)
- Check cross-pagination
- Reorder some items if needed (e.g. - concepts by difficulty)
- Group some items if needed (promo & history & mission ...)
- (Maybe) Add old decompose view for compatability
- Add redirect page map (for old users)

</details>

### TODO

> **Legend:**
> - 🚀 TUTORIAL (get started)
> - 🛠 GUIDE (guides & examples)
> - 🧩 EXPLANATION (concepts)
> - 📚 UNDERSTANDING (reference)
> - 🍰 ABOUT

- ~~🚀 int/Promotion at company =>  🍰 /promo/Promotion at company~~
- ~~🚀 int/Integration at team, 🚀 int/Partial application  =>  🍰 /promo/Integration at team~~
- ~~🚀 int/Cheatsheet, 🚀 Decompose logic => 🚀 Cheatsheet~~
- ~~🚀 int/Adv & Disadv => 🍰 /Adv & Disadv~~
- ~~🚀 tut/Decompose logic, 🚀 tut/Decompose design layouts => 🚀 Decomposing logic~~
- ~~🚀 tut/QuickStart => 🚀 QuickStart~~
- ~~🚀 Alternatives/* => 🍰 /Alternatives/*~~
- ~~🚀 Motivation => 🚀 Motivation (basely),  🍰 Motivation (completely)~~
- 🧩 Needs-driven => 🧩Domain-first, 🧩Needs-driven
- 🧩 Naming adaptivity => 🧩Naming
- 🧩 App splitting => 🧩Decomposition
- ~~🛠 Decouple entities =>  🧩  Decouple entities (FIXME)~~
- ~~🛠 Low Coupling & High Cohesion =>  🧩  Isolation~~
- ~~🛠 /White-labels =>🛠 /examples/White-labels~~
- ~~🛠 /Monorepo =>🛠 /examples/Monorepo~~
- ~~🛠 Handbook/* => 🧩 Handbook/* (`TODO: and change name`)~~
- ~~🍰 Community, 🍰 Team => 🍰 Team~~

**Comment by azinit** [comment]
Хотя уже понятно, что в процессе придется щас перелопатить чутка реструктуризацию 🤔
